### PR TITLE
Make all tables sortable

### PR DESCRIPTION
**Pull request by tme321**
Alright a bit bigger this time, but basically just adding the same sorting interface functionality to all the tables (that I could find anyway).

I have created a generic [table header component](https://github.com/tme321/poestack-next/blob/f21814aa2f30451f4bf98c562cdcbecfcb9c8f74/src/components/sortable-table-header.tsx) that does what the code did before in the characters page.

I also created a [use sortable hook](https://github.com/tme321/poestack-next/blob/f21814aa2f30451f4bf98c562cdcbecfcb9c8f74/src/hooks/use-sort-th-hook.ts) for the hook functionality previously in use.

So a [set of column definitions](https://github.com/tme321/poestack-next/blob/f21814aa2f30451f4bf98c562cdcbecfcb9c8f74/src/pages/poe/characters/index.tsx#L77) can be used to [drive the new hook](https://github.com/tme321/poestack-next/blob/f21814aa2f30451f4bf98c562cdcbecfcb9c8f74/src/pages/poe/characters/index.tsx#L154) whose callback is where you can respond to changes in the sorting behavior.

Then the [sortable header component](https://github.com/tme321/poestack-next/blob/f21814aa2f30451f4bf98c562cdcbecfcb9c8f74/src/pages/poe/characters/index.tsx#L365) can be used where a `thead` element would normally go.  The result is the same behavior as previously based on your changes to prod of my previous pull request.

If that hook callback doesn't work with how you need to update queries in any of the other pages let me know and I'll see about making changes to support whatever is missing.

### CODE REVIEW

**Review by zach-herridge — CHANGES_REQUESTED** [review]
This looks good but it seems to be causing some issues.
- Once you navigate to the character page you cannot navigate away
- On the character page there is state loop introduced where the page constantly refetches the search when no changes have been made

**Comment by tme321** [comment]
I'll look into it

**Comment by tme321** [comment]
Ok I believe that should fix the issue.  It fixed it in dev and build runs ok.

**Comment by zach-herridge** [comment]
Looks good merged it in thanks!

**Pull request merged**
